apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  PAYMENT_API_KEY: {{ .Values.olaresEnv.PAYMENT_API_KEY | quote }}
  PAYMENT_API_SECRET: {{ .Values.olaresEnv.PAYMENT_API_SECRET | quote }}
  PAYMENT_WEBHOOK_SECRET: {{ .Values.olaresEnv.PAYMENT_WEBHOOK_SECRET | quote }}
